# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12r7Lg_B2u43D6iVvjg9OfegEystkXojm
"""

import pandas as pd
df = pd. read_csv('credit_risk_dataset.csv')

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

df_clean = df.dropna()
x_raw = df_clean.drop('loan_status', axis=1)
x = pd.get_dummies(x_raw, drop_first=True)
y = df_clean['loan_status']

df.info()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

# Initialize 'Predicted_Risk_Score' column in df with NaN to handle rows that were dropped
df['Predicted_Risk_Score'] = None
# Assign predictions to the corresponding rows in the original df using the index from x
df.loc[x.index, 'Predicted_Risk_Score'] = model.predict_proba(x)[:, 1]

display(df.head())

df.to_csv('credit_risk_tableau_ready.csv', index=False)
